apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: gaida
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gaida
  template:
    metadata:
      labels:
        app: gaida
    spec:
      containers:
        - name: gaida
          image: zacharyyoung0/gaida:0.1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
